services:
  ecs_dev_ubuntu_template:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    container_name: ecs_dev_ubuntu_template
    hostname: ecs_dev_ubuntu_template
    shm_size: '4gb'
    volumes:
      - $PWD/:/workspace:cached
    environment:
      GIT_AUTHOR_NAME: ${GIT_USERNAME}
      GIT_COMMITTER_NAME: ${GIT_USERNAME}
      GIT_AUTHOR_EMAIL: ${GIT_EMAIL_ADDRESS}
      GIT_COMMITTER_EMAIL: ${GIT_EMAIL_ADDRESS}
      TZ: Asia/Tokyo
    tty: true
